name: HelloWorld
on: push
jobs:
  hello-world-jobs:
    runs-on: ubuntu-latest # VM ubuntu pour faire tourner ubuntu
    steps:
      - uses: actions/checkout@v4
      - run: echo "hello world"
      # - run: bats -v